const players = [
  { username: "AgentK_0081", callsign: "FED001", rank: "Director", suspended: false },
  { username: "MinPRPO08", callsign: "FED014", rank: "Special Agent", suspended: false },
  { username: "crnac", callsign: "FED022", rank: "Probationary Special Agent", suspended: true }, 
  { callsign: "FED001", username: "HIM12345t", rank: "Director" },
  { callsign: "FED002", username: "AgentK_0081", rank: "Deputy Director" },
  { callsign: "FED003", username: "foohm123", rank: "Assistant Director" },
  { callsign: "FED004", username: "Kris", rank: "Assistant Director" },
  { callsign: "FED005", username: "AgentYeet1122", rank: "Assistant Director In-charge" },
  { callsign: "FED006", username: "JohnLis912", rank: "Experienced Supervisory Special Agent" },
  { callsign: "FED007", username: "Koruman3431", rank: "Directors [Division]" },
  { callsign: "FED008", username: "TheMentalSakura", rank: "Directors [Division]" },
  { callsign: "FED009", username: "Lucss123450", rank: "Experienced Supervisory Special Agent" },
  { callsign: "FED015", username: "kingsleykee3", rank: "Experienced Supervisory Special Agent" },
  { callsign: "FED017", username: "sw40f", rank: "Senior Special Agent" },
  { callsign: "FED018", username: "12thomas_mth", rank: "Directors [Division]" },
  { callsign: "FED021", username: "lo12io", rank: "Experienced Special Agent" },
  { callsign: "FED022", username: "Oggy3545", rank: "Probationary Special Agent" },
  { callsign: "FED023", username: "Xczosnekx", rank: "Assistant Special Agent in Charge" },
  { callsign: "FED024", username: "KILLER_FF12345", rank: "Special Agent" },
  { callsign: "FED025", username: "Mstar25jy2", rank: "Special Agent in Charge" },
  { callsign: "FED026", username: "Aviorum", rank: "Probationary Special Agent" },
  { callsign: "FED027", username: "apple34555", rank: "Probationary Special Agent" },
  { callsign: "FED028", username: "energyfire2020", rank: "Senior Special Agent" },
  { callsign: "FED029", username: "RushoRoblox", rank: "Special Agent" },
  { callsign: "FED030", username: "CallmePrinzzzz", rank: "Experienced Special Agent" },
  { callsign: "FED031", username: "tomatocakelikeme", rank: "Experienced Special Agent" },
  { callsign: "FED032", username: "NoobiiFr", rank: "Special Agent" },
  { callsign: "FED033", username: "wAzup2029", rank: "Special Agent" },
  { callsign: "FED034", username: "smileyhorseshoe", rank: "Probationary Special Agent" },
  { callsign: "FED035", username: "Skymitar_1", rank: "Special Agent" },
  { callsign: "FED037", username: "chathho", rank: "Probationary Special Agent" },
  { callsign: "FED040", username: "TheOriginalAaron", rank: "Probationary Special Agent" },
  { callsign: "FED042", username: "InspetorRodrigo13", rank: "Probationary Special Agent" },
  { callsign: "FED044", username: "Olga_BANPRO", rank: "Special Agent" },
  { callsign: "FED045", username: "Agent_Bloom4", rank: "Special Agent" },
  { callsign: "FED047", username: "miska20210", rank: "Probationary Special Agent" },
  { callsign: "FED050", username: "depascal123456", rank: "Probationary Special Agent" },
  { callsign: "FED051", username: "yo_fish4656", rank: "Probationary Special Agent" },
  { callsign: "FED056", username: "crafmaster2020", rank: "Special Agent" },
  { callsign: "FED067", username: "heisenburguhh", rank: "Special Agent" },
  { callsign: "FED087", username: "Umutuchiha22", rank: "Probationary Special Agent" },
  { callsign: "FED091", username: "Dino_456387", rank: "Special Agent" },
  { callsign: "FED100", username: "federicopisy1", rank: "Experienced Special Agent" },
  { callsign: "FED112", username: "pandapkju", rank: "Experienced Special Agent" },
  { callsign: "FED120", username: "DaCapybara", rank: "Experienced Supervisory Special Agent" },
  { callsign: "FED126", username: "Dragonflames30007", rank: "Experienced Special Agent" },
  { callsign: "FED198", username: "ErichHans1944", rank: "Special Agent" },
  { callsign: "FED200", username: "natepogi06", rank: "Experienced Special Agent" },
  { callsign: "FED214", username: "tobecontinud12", rank: "Special Agent" },
  { callsign: "FED216", username: "huylatui12345", rank: "Special Agent" },
  { callsign: "FED315", username: "moosehead_v2", rank: "Probationary Special Agent" },
  { callsign: "FED404", username: "Ghxsty1102", rank: "Probationary Special Agent" },
  { callsign: "FED528", username: "Mateusz_FBI", rank: "Special Agent" },
  { callsign: "FED650", username: "MahliTechBro", rank: "Special Agent" },
  { callsign: "FED666", username: "aDemoness", rank: "Special Agent" },
  { callsign: "FED667", username: "Yan", rank: "Probationary Special Agent" },
  { callsign: "FED740", username: "Generalalex394121", rank: "Probationary Special Agent" },
  { callsign: "FED742", username: "Toxic36176", rank: "Probationary Special Agent" },
  { callsign: "FED777", username: "Alexplaysroblox11xd", rank: "Special Agent" },
  { callsign: "FED993", username: "thorodinson_921", rank: "Probationary Special Agent" },
  { callsign: "FED999", username: "UltimateRobo2457", rank: "Experienced Supervisory Special Agent" },
];
